version: 2

models:
  - name: DIM_FILM_CHARACTERS
    description: One row per character per film appearance, from STG_FILMS.
    columns:
      - name: APPEARANCE_ID
        description: Primary key.
      - name: FILM_ID
        description: Key link to INT_FILMS
      - name: CHARACTER_ID
        description: Key link to INT_CHARACTERS
      - name: FILM_TITLE
        description: Film title.
      - name: EPISODE
        description: Film episode number.
      - name: CHARACTER_NAME
        description: Name of character.
  - name: FCT_CHARACTER_APPEARANCE_COUNTS
    description: Counts of the number of films each character has appeared in, sorted in descending order.