version: 2

models:
  - name: stg_films
    description: Staging of the raw films dataset from SWAPI.
    columns:
      - name: film_id
        description: Primary key of the dataset.
        tests:
          - unique
          - not_null
      - name: film_title
        description: Title of the film.
      - name: episode
        description: Episode number of the film.
      - name: opening_crawl
        description: Opening text crawl in film intro.
      - name: director
        description: Director of the film.
      - name: producer
        description: Producer(s) of the film.
      - name: release_date
        description: Date of film release (US).
      - name: characters
        description: Array of characters that appear in the film. Relates to raw.people.
      - name: planets
        description: Array of planets that appear in the film. Relates to raw.planets.
      - name: species
        description: Array of species that appear in the film. Relates to raw.species.
      - name: starships
        description: Array of starships that appear in the film. Relates to raw.starships.
      - name: vehicles
        description: Array of vehicles that appear in the film. Relates to raw.vehicles.
      - name: url
        description: Web address for the resource in SWAPI.
      - name: created_date
        description: Date the record was created in SWAPI.
      - name:  edited_date
        description: Date the record was last edited in SWAPI.